on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Gno Test
    uses: ./.github/workflows/test.yaml
  generate:
    name: Generate
    uses: ./.github/workflows/generate.yaml
